### ISSUE TITLE
Support additional input_html options

### ISSUE THREAD

**Issue by pedroteixeira** [demersus/formtastic_datepicker_inputs#3]
The input ignores input_html.. Something the following would work:

def date_picker_options(format, opts, value = nil)

input_opts = {:class => 'ui-date-picker',:value => value.try(:strftime, format)}
     input_opts[:class] = input_opts[:class].concat(opts[:class]) if opts[:class]
      input_opts = opts[:input_html].merge(input_opts) if opts[:input_html]

```
  opts.merge({:input_html => input_opts})
```

end

**Comment by demersus** [comment]
Good point.    I will update the master branch with these changes.
